### PR TITLE
Virtual environment header for cli

### PR DESCRIPTION
**Pull request by rmrhz**
Adding `#!/usr/bin/env php` will enable users to run `cli` without explicitly defining `php cli`

### CODE REVIEW

**Comment by kjdion84** [comment]
YOU. KICK. ASS.

**Comment by kjdion84** [comment]
1 prob. Doesn't seem to work from the git bash. Will look into this.

I get "bash: cli: command not found"

**Comment by kjdion84** [comment]
Looks like this only works on *nix...damn...will be reverting this until I can find a solution for the 3 big OS.

**Comment by rmrhz** [comment]
@kjdion84 ahhh in windows you really need to specify `php cli`. Other than that you can create a batch script.

```batch
@php "cli" %*
```

**Pull request merged**
