### PR TITLE
Remove .gitignore & vendor/

### PR DESCRIPTION
**Pull request by rmrhz**
Adding a `.gitignore` file and removing the `vendor/` directory would be a better move as you specify in your `composer.json` that you will install from the master branch of the packages specified. You have to deal with committing every change in the `vendor` directory when you run composer update. Committing the `composer.lock` would be a safe move.

### CODE REVIEW

**Comment by kjdion84** [comment]
Thanks, this is an awesome idea! My only issue is that I use PHPStorm to declare ignored files, so I would also need to add the .idea/ directory, and a file I called "todo" which contains my todo list to the gitignore. Thoughts?

**Comment by rmrhz** [comment]
I asked a colleague of mine about it and it would be better to ignore it off. I also included to ignore Mac's `.DS_Store` file

**Comment by kjdion84** [comment]
I'm not going to merge this one because I would like to collab with you and get a complete .gitignore file going which will include all ignores we want across both of our systems. Cool?

**Comment by rmrhz** [comment]
Fine by me :)

**Comment by kjdion84** [comment]
So from what I gather:

.idea/
vendor/
todo
.DS_Store

**Pull request closed without merging**
